variables_of_interest:
  - "s1"
  - "s2"
  - "f200like"
energies:
  range:
    - 2
    - 70
epochs:
  7000
epochCheck:
  20
batchSize:
  1000
noiseSize:
  1000
metric:
  - "accuracy"
  - "moments"
g_rate:
  0.0005
d_rate:
  0.0005
g_beta1:
  0.3
d_beta1:
  0.3
verbose:
  False
overrides:
  d_nodes:
    [200,200]
  g_nodes:
    [200,200]
  dropout:
    [0.2,0.2]