variables_of_interest:
  - "s1"
  - "s2"
  - "f200like"
energies:
  range:
    - 10
    - 20
epochs:
  4
epochCheck:
  4
batchSize:
  1000
noiseSize:
  1000
metric:
  - "accuracy"
  - "moments"
g_rate:
  0.0005
d_rate:
  0.0005
g_beta1:
  0.3
d_beta1:
  0.3
verbose:
  False
overrides:
  d_nodes:
    [15,25]
  g_nodes:
    [65,75]
  dropout:
    [0.1,0.2]