# This is a basic workflow to help you get started with Actions

name: Check Status

# Controls when the action will run.
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check-if-done:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Checking if process is done
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /hepgpu5-data1/ricozl/ricozl/mphys-project/Standalone/
          bash check_if_done.sh
          
    - name: Send email
      if: success()
      run: |
        echo "I would send email here.." 

