# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validating-yaml-files:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1

    - name: Install pykwalify
      run: |
        pip3 install pykwalify PyYAML

    - name: General Config Validation
      run: |
        cd Training/tests
        python3 config_test.py

    - name: Discriminator Layout Validation
      run: |
        cd Training/tests
        python3 discriminator_test.py

    - name: Generator Layout Validation
      run: |
        cd Training/tests
        python3 generator_test.py

  deploying-master:
      runs-on: [ubuntu-latest]
      steps:
      - name: Deploying to github registry
        run: |
          echo ${{ secrets.GITHUB_REGISTRY_TOKEN }} | docker login docker.pkg.github.com -u enricozammitlon --password-stdin
          docker build --target analysis --cache-from docker.pkg.github.com/enricozammitlon/gan4ds/argan:analysis --pull -t docker.pkg.github.com/enricozammitlon/gan4ds/argan:analysis Dockerfile.devcontainer
          docker push docker.pkg.github.com/enricozammitlon/gan4ds/argan:analysis